### ISSUE TITLE
How to install React based version?

### ISSUE THREAD

**Issue by RinatValiullov** [iqonicdesignofficial/hope-ui-design-system#1]
I did not see a clear algorithm for installing a React template from this design system.
Where is [`CODE-REACT`](https://templates.iqonic.design/hope-ui/documentation/react/build/gulp) folder? What I must to do for using this library?

**Comment by chiragmistry007** [comment]
Hi 
You can use this
https://github.com/iqonicdesignofficial/hope-ui-react-dashboard

Code React is for download through our iqonic.design platform.
