### ISSUE TITLE
Found Some Spelling Mistakes on Maintenance page.

### ISSUE THREAD

**Issue by vikramsamak** [iqonicdesignofficial/hope-ui-design-system#2]
Here 
1. It will not take a long time till we get the error **fiked.**
-->It will not take a long time till we get the error **fixed.**

2. We **wii** live again in
--> We **will** live again in,

![image](https://user-images.githubusercontent.com/95061742/199163173-0dc3a97a-6072-466c-a2dd-9acef613f933.png)

**Comment by chiragmistry007** [comment]
Hi
we can fix this in our next update
